namespace Shared;

public record ZoneModel(
    string name,
    string zoneType,
    GridRect? gridRect,
    MyRect? rect,
    string properties,
    bool autoGenerated
)
{
    public MyRect GetRect(int tileSize)
    {
        if (rect != null)
        {
            return rect.Value;
        }
        else if (gridRect != null)
        {
            return gridRect.Value.GetRect(tileSize);
        }
        throw new Exception("Bad ZoneModel");
    }
}